- hosts: databases
  become: yes
  tasks:
    - name: Ensure that MariaDB is installed
      yum:
        name:
          - mariadb-server
          - MySQL-python
    - name: Ensure that MariaDB is started and enabled
      service: name=mariadb state=started enabled=yes
    - name: Set the root password for MySQL
      mysql_user:
        name: root
        password: admin
        state: present
    - name: Upload the .my.cnf file to save the credentials
      copy:
        src: my.conf
        dest: /root/.my.cnf
        owner: root
        mode: 0600

